e-com/app_order/urls.py
from django.urls import path
from app_order import views

app_name = 'app_order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('cart/', views.cart_view, name="cart"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
    path('applycoupon/<int:order_id>/', views.apply_coupon_view, name="applycoupon"),
    path('removecoupon/<int:order_id>/', views.remove_coupon_view, name="removecoupon"),
]

e-com/app_shop/urls.py
from django.urls import path
from app_shop import views

app_name = 'app_shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('SallerUploadProduct/', views.Saller_upload_product, name='SallerUploadProduct'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('CreateCoupon/', views.create_coupon, name='CreateCoupon'),
    path('sallerproductlist/', views.saller_product_list_view, name='sallerproductlist'),
    path('deleteproduct/<int:pk>', views.saller_product_delete_view, name='deleteproduct'),
]

e-com/e_com/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_shop.urls')),
    path('account/', include('app_login.urls')),
    path('shop/', include('app_order.urls')),
    path('payment/', include('app_payment.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e-com/app_shop/models.py
from django.db import models
from app_login.models import User

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"

class Product(models.Model):
    product_Saller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="vendor", null=True, blank=True)
    mainimage = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=264)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Description')
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created',]


class Coupon(models.Model):
    vendor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="coupon_vendor", null=True)
    code = models.CharField(max_length=255, verbose_name='Coupon Code', null=True)
    short_desc = models.TextField(max_length=500, null=True, verbose_name='Short Description')
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.FloatField(null=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.code}'

e-com/app_shop/forms.py
from django import forms
from app_shop.models import Coupon, Product

class SallerUploadForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            "mainimage",
            "name",
            "category",
            "preview_text",
            "detail_text",
            "price",
            "old_price"
        )

class CouponForm(forms.ModelForm):
    class Meta:
        model = Coupon
        fields = (
            "code",
            "short_desc",
            "valid_from",
            "valid_to",
            "discount"
        )

        widgets = {
            'valid_from': forms.TextInput(attrs={'type':'datetime-local'}),
            'valid_to': forms.TextInput(attrs={'type':'datetime-local'})
        }

e-com/app_shop/views.py
from django.shortcuts import render, get_object_or_404

# Import views
from django.views.generic import ListView, DetailView

# Models
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from app_login.models import User
from app_shop.models import Product
from app_shop.forms import *

# Mixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.



class Home(ListView):
    model = Product
    template_name = 'app_shop/home.html'

class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'app_shop/product_detail.html'



@login_required(login_url='app_login:login')
def Saller_upload_product(request):
    form = SallerUploadForm()
    # print(request.user.user_type)
    if request.method == "POST" and request.user.user_type == "Saller":
        form = SallerUploadForm(request.POST, request.FILES)
        if form.is_valid():
            product_obj = form.save(commit=False)
            product_obj.product_Saller = request.user
            # print(product_obj)
            product_obj.save()
            messages.success(request, "your product added successfully!")
            return redirect("app_shop:SallerUploadProduct")

        elif request.user.user_type == "Buyer":
            messages.warning(request, "you are not a Saller. Can't add Products")
            return redirect("app_shop:home")


    context ={
        'form': form
    }
    return render(request, 'app_shop/saller_upload_product.html', context)



@login_required(login_url='app_login:login')
def create_coupon(request):
    form = CouponForm()
    if request.method == "POST" and request.user.user_type == "Saller":
        form = CouponForm(request.POST)
        if form.is_valid():
            coupon_obj = form.save(commit=False)
            coupon_obj.vendor = request.user
            coupon_obj.save()
            messages.success(request, "your coupon added successfully!")
            return redirect("app_shop:CreateCoupon")

    context = {
        'form': form,
    }
    return render(request, 'app_shop/create_coupon.html', context)

@login_required(login_url='app_login:login')
def saller_product_list_view(request):
    if request.user.user_type == "Saller":
        products = Product.objects.filter(product_Saller = request.user)

        context = {
            'products':products
        }
        
    else:
        context = {}
        
    return render(request, 'app_shop/saller_product_list.html', context)

@login_required(login_url='app_login:login')
def saller_product_delete_view(request, pk):
    if request.user.user_type == "Saller":
        product = get_object_or_404(Product, id=pk)
        product.delete()
        messages.success(request, "your product delete successfully!")
        return redirect("app_shop:sallerproductlist")
    else:
        return redirect("app_shop:home")

e-com/templates/app_shop/create_coupon.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create Coupon {% endblock %}
{% block body_block %}
<form method="POST" enctype="multipart/form-data">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-warning btn-sm">Save</button>
</form>
<br>
<br>

{% endblock %}

e-com/templates/app_shop/home.html
{% extends 'base.html' %}
{% block title_block %} Home {% endblock %}
{% block body_block %}

<div class="container my-5">
  <h2 class="my-5">Featured Products</h2>
  <div class="row">
    {% for product in object_list %}
    <div class="col-md-6 col-sm-12 col-lg-3">
      <figure class="card card-product">
        <div class="img-wrap" style="padding: 1rem;">
          <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
        </div>
        <figcaption class="info-wrap">
          <h6 class="title"><a href="{% url 'app_shop:product_detail' pk=product.pk %}">{{product.name}}</a></h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
              <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
              <span class="price-old"><strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
            </div>
          </div>
        </figcaption>
        <a href="{% url 'app_shop:product_detail' pk=product.pk %}" class="btn btn-info">Buy Now</a>
      </figure>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

e-com/templates/app_shop/product_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
  <div class="card">
    <div class="row">
      <aside class="col-sm-5 border-right">
        <article class="gallery-wrap">
          <div class="img-big-wrap">
            <div>
              <a href="#"><img src="/media/{{object.mainimage}}" style="width:450px"></a>
            </div>
          </div>
        </article>
      </aside>
      <aside class="col-sm-7">
        <article class="card-body p-5">
          <h3 class="title mp-3">{{object.name}}</h3>
          <p class="price-detail-wrap">
            <span class="price h3 text-warning">
              <span class="currency">BDT &#2547;</span><span class="num">{{object.price}}</span>
            </span>
          </p>
          <dl class="item-property">
            <dt>Description</dt>
            <dd>
              <p>{{object.detail_text|linebreaks}}</p>
            </dd>
          </dl>
          {% for coupon in object.product_Saller.coupon_vendor.all %}
          <div class="alert alert-primary" role="alert">
            <strong>Code: {{ coupon.code }} | Discount: &#2547;{{ coupon.discount }}% (Copy the coupon code)</strong>
            <br>
          </div>
          {% endfor %}
          <br>
          {% if request.user.user_type == "Buyer" %}
          <a href="{% url 'app_order:add' pk=object.pk %}" class="btn btn-lg btn-outline-primary text-uppercase">
            <i class="fas fa-shopping-cart"></i> Add to Cart</a>
          {% endif %}
        </article>
      </aside>
    </div>
  </div>
</div>
{% endblock %}

e-com/templates/app_shop/saller_product_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Product List {% endblock %}
{% block body_block %}
<div class="">
    <h4>USER: {{ request.user.email }} ({{ request.user.user_type }})</h4>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Details</th>
                    <th scope="col">Update</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <th scope="col">{{forloop.counter}}</th>
                    <th scope="col">{{product.name}}</th>
                    <th scope="col">{{product.price}}</th>
                    <th scope="col"><a href="#" class="btn btn-sm btn-outline-primary">Details</a></th>
                    <th scope="col"><a href="#" class="btn btn-sm btn-info">Update</a></th>
                    <th scope="col"><a href="{% url 'app_shop:deleteproduct' pk=product.id %}"
                            class="btn btn-sm btn-danger">Delete</a></th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

e-com/templates/app_shop/saller_upload_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Saller Product Upload {% endblock %}
{% block body_block %}
<form method="POST" enctype="multipart/form-data">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-warning btn-sm">Save</button>
</form>
<br>
<br>
{% endblock %}