e-com/app_order/urls.py
from django.urls import path
from app_order import views

app_name = 'app_order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('cart/', views.cart_view, name="cart"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
    path('applycoupon/<int:order_id>/', views.apply_coupon_view, name="applycoupon"),
    path('removecoupon/<int:order_id>/', views.remove_coupon_view, name="removecoupon"),
]

e-com/app_payment/urls.py
from django.urls import path
from app_payment import views

app_name = "app_payment"

urlpatterns = [
    path('checkout/', views.checkout, name="checkout"),
    path('pay/', views.payment, name="payment"),
    path('status/', views.complete, name="complete"),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name="purchase"),
    path('orders/', views.order_view, name="orders"),
]

e-com/app_shop/urls.py
from django.urls import path
from app_shop import views

app_name = 'app_shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('SallerUploadProduct/', views.Saller_upload_product, name='SallerUploadProduct'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('CreateCoupon/', views.create_coupon, name='CreateCoupon'),
    path('sallerproductlist/', views.saller_product_list_view, name='sallerproductlist'),
    path('deleteproduct/<int:pk>', views.saller_product_delete_view, name='deleteproduct'),
]

e-com/e_com/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_shop.urls')),
    path('account/', include('app_login.urls')),
    path('shop/', include('app_order.urls')),
    path('payment/', include('app_payment.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e-com/app_order/models.py
from tkinter import CASCADE
from django.db import models
from django.conf import settings

# Model
from app_shop.models import Coupon, Product
# Create your models here.

class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="cart")
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.quantity} X {self.item}'

    def get_total(self):
        total = self.item.price * self.quantity
        float_total = format(total, '0.2f')
        return float_total

    def coupon_discount(self, discount=0):
        discount = (self.item.price * self.quantity*discount)/100
        return discount


    


class Order(models.Model):
    orderitems = models.ManyToManyField(Cart)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    paymentId = models.CharField(max_length=264, blank=True, null=True)
    orderId = models.CharField(max_length=200, blank=True, null=True)
    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, null=True)
    applycoupon = models.BooleanField(default=False)

    def get_totals(self):
        total = 0
        for order_item in self.orderitems.all():
            total += float(order_item.get_total())
        return total - self.get_total_discount()

    def get_total_discount(self):
        total_discount = 0
        # print(self.applycoupon)
        if self.applycoupon:
            # print(self.orderitems.all(), self.coupon)
            # print(self.orderitems.filter(item__product_Saller = self.coupon.vendor))
            for d_item in self.orderitems.filter(item__product_Saller = self.coupon.vendor):
                total_discount += d_item.coupon_discount(self.coupon.discount)

        # print(total_discount)
        return total_discount

    def apply_coupon(self, coupon):
        self.coupon = coupon
        self.applycoupon = True
        self.save()

    def remove_coupon(self):
        self.coupon = None
        self.applycoupon = False
        self.save()

    

e-com/app_order/views.py
from ast import Or
from django.shortcuts import render, get_object_or_404, redirect

# Authentications
from django.contrib.auth.decorators import login_required

# Model
from app_order.models import Cart, Order
from app_shop.models import *
# Messages
from django.contrib import messages
# datetime
from django.utils import timezone
# Create your views here.

@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    print("Item")
    print(item)
    order_item = Cart.objects.get_or_create(item=item, user=request.user, purchased=False)
    print("Order Item Object:")
    print(order_item)
    print(order_item[0])
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    print("Order Qs:")
    print(order_qs)
    #print(order_qs[0])
    if order_qs.exists():
        order = order_qs[0]
        print("If Order exist")
        print(order)
        if order.orderitems.filter(item=item).exists():
            order_item[0].quantity += 1
            order_item[0].save()
            messages.info(request, "This item quantity was updated.")
            return redirect("app_shop:home")
        else:
            order.orderitems.add(order_item[0])
            messages.info(request, "This item was added to your cart.")
            return redirect("app_shop:home")
    else:
        order = Order(user=request.user)
        order.save()
        order.orderitems.add(order_item[0])
        messages.info(request, "This item was added to your cart.")
        return redirect("app_shop:home")


@login_required
def cart_view(request):
    carts = Cart.objects.filter(user=request.user, purchased=False)
    orders = Order.objects.filter(user=request.user, ordered=False)
    if carts.exists() and orders.exists():
        order = orders[0]
        return render(request, 'app_order/cart.html', context={'carts':carts, 'order':order})
    else:
        messages.warning(request, "You don't have any item in your cart!")
        return redirect("app_shop:home")


@login_required
def remove_from_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
            order.orderitems.remove(order_item)
            order_item.delete()
            messages.warning(request, "This item was removed form your cart")
            return redirect("app_order:cart")
        else:
            messages.info(request, "This item was not in your cart.")
            return redirect("app_shop:home")
    else:
        messages.info(request, "You don't have an active order")
        return redirect("app_shop:home")

@login_required
def increase_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
            if order_item.quantity >= 1:
                order_item.quantity += 1
                order_item.save()
                messages.info(request, f"{item.name} quantity has been updated")
                return redirect("app_order:cart")
        else:
            messages.info(request, f"{item.name} is not in your cart")
            return redirect("app_shop:home")
    else:
        messages.info(request, "You don't have an active order")
        return redirect("app_shop:home")


@login_required
def decrease_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                messages.info(request, f"{item.name} quantity has been updated")
                return redirect("app_order:cart")
            else:
                order.orderitems.remove(order_item)
                order_item.delete()
                messages.warning(request, f"{item.name} item has been removed from your cart")
                return redirect("app_order:cart")
        else:
            messages.info(request, f"{item.name} is not in your cart")
            return redirect("app_shop:home")
    else:
        messages.info(request, "You don't have an active order")
        return redirect("app_shop:home")

@login_required
def apply_coupon_view(request, order_id):
    now = timezone.now()

    if request.method == 'POST':
        coupon_code = request.POST.get('code', None)
        coupon = Coupon.objects.filter(code=coupon_code)
        order = Order.objects.filter(id= order_id)

        if coupon.exists() and order.exists():
            coupn_end_date= coupon[0].valid_to
            if coupn_end_date > now:
                order[0].apply_coupon(coupon[0])
            else:
                messages.error(request, "your coupon is expired!")
        else:
            messages.warning(request, "You entered wrong coupon code! Please enter curract coupon.")

        return redirect("app_order:cart")

        
@login_required
def remove_coupon_view(request, order_id):
    order = Order.objects.filter(id= order_id)
    # print(order)
    if order.exists():
        order[0].remove_coupon()
    else:
        messages.warning(request, "You didn't have any coupon!")

    return redirect("app_order:cart")

e-com/templates/app_order/cart.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
  <div class="my-5">
    <h2>Your Cart</h2>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col" width="15%">#</th>
        <th scope="col">Product Name</th>
        <th scope="col">Quantity</th>
        <th scope="col" align="right">Price</th>
        <th scop="col">Remove</th>
      </tr>
    </thead>
    <tbody>
      {% for cart in carts %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{cart.item.name}}</td>
        <td>
          <a class="mr-2" href="{% url 'app_order:decrease' pk=cart.item.pk %}"><span class="badge badge-light"><i
                class="fas fa-minus"></i></span></a>
          {{ cart.quantity }}
          <a class="mr-2" href="{% url 'app_order:increase' pk=cart.item.pk %}"> <span class="badge badge-light"> <i
                class="fas fa-plus"></i></span></a>
        </td>
        <td align="right">&#2547; {{cart.get_total}}</td>
        <td><a href="{% url 'app_order:remove' pk=cart.item.pk %}" class="btn btn-danger btn-sm">Remove From Cart</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="row">
    <div class="col-sm-6 col-md-6">
      {% if not order.applycoupon %}
      <form method="POST" action="{% url 'app_order:applycoupon' order_id=order.id %}">
        {% csrf_token %}
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Enter Coupon Code" name="code">
          <div class="input-group-append">
            <button type="submit" class="btn btn-info" id="basic-addon2">Add Coupon</button>
          </div>
        </div>
      </form>
      <ul>
        <li>N.B: you have just one chance to use coupon. </li>
      </ul>
      {% else %}
      <div class="alert alert-warning" role="alert">
        You already used your coupon! If you want to use another coupon before checkout please press &nbsp;<a
          href="{% url 'app_order:removecoupon' order_id=order.id %}" class="btn btn-danger btn-sm">Remove Coupon</a>
      </div>
      {% endif %}
    </div>
    <div class="col-sm-6 col-md-6">
      <div class="alert alert-dark" role="alert">
        {% if order.applycoupon %}
        <h5 class="text-center"><strong>Sub Total: </strong> &#2547;
          {{order.get_totals|add:order.get_total_discount | floatformat:2 }}</h5>
        <h5 class="text-center"><strong>Discount: </strong> - &#2547; {{order.get_total_discount | floatformat:2 }}</h5>
        {% endif %}
        <h5 class="text-center"><strong>Total: </strong> &#2547; {{order.get_totals | floatformat:2 }}</h5>
      </div>
      <div>
        <a href="{% url 'app_shop:home' %}" class="btn btn-warning mr-4">Continue Shoping</a>
        <a href="{% url 'app_payment:checkout' %}" class="btn btn-success mr-4">Proceed To Checkout</a>
      </div>
    </div>
  </div>

</div>
{% endblock %}