e-com/app_login/urls.py
from django.urls import path
from app_login import views
app_name = 'app_login'



urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

e-com/app_order/urls.py
from django.urls import path
from app_order import views

app_name = 'app_order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('cart/', views.cart_view, name="cart"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
    path('applycoupon/<int:order_id>/', views.apply_coupon_view, name="applycoupon"),
    path('removecoupon/<int:order_id>/', views.remove_coupon_view, name="removecoupon"),
]

e-com/app_payment/urls.py
from django.urls import path
from app_payment import views

app_name = "app_payment"

urlpatterns = [
    path('checkout/', views.checkout, name="checkout"),
    path('pay/', views.payment, name="payment"),
    path('status/', views.complete, name="complete"),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name="purchase"),
    path('orders/', views.order_view, name="orders"),
]

e-com/app_shop/urls.py
from django.urls import path
from app_shop import views

app_name = 'app_shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('SallerUploadProduct/', views.Saller_upload_product, name='SallerUploadProduct'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('CreateCoupon/', views.create_coupon, name='CreateCoupon'),
    path('sallerproductlist/', views.saller_product_list_view, name='sallerproductlist'),
    path('deleteproduct/<int:pk>', views.saller_product_delete_view, name='deleteproduct'),
]

e-com/e_com/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_shop.urls')),
    path('account/', include('app_login.urls')),
    path('shop/', include('app_order.urls')),
    path('payment/', include('app_payment.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e-com/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <title>E-com |{% block title_block %} {% endblock %}</title>

  <style>
    .card {
      height: 350px;
    }

    .card-product:after {
      content: "";
      display: table;
      clear: both;
      visibility: hidden;
    }

    .card-product .price-new,
    .card-product .price {
      margin-right: 5px;
    }

    .card-product .price-old {
      color: #999;
    }

    .card-product .img-wrap {
      border-radius: 3px 3px 0 0;
      overflow: hidden;
      position: relative;
      height: 220px;
      text-align: center;
    }

    .card-product .img-wrap img {
      max-height: 100%;
      max-width: 100%;
      object-fit: cover;
    }

    .card-product .info-wrap {
      overflow: hidden;
      padding: 15px;
      border-top: 1px solid #eee;
    }

    .card-product .action-wrap {
      padding-top: 4px;
      margin-top: 4px;
    }

    .card-product .bottom-wrap {
      padding: 15px;
      border-top: 1px solid #eee;
    }

    .card-product .title {
      margin-top: 0px;
    }
  </style>
</head>

<body>
  {% include 'navbar.html' %}
  <div class="container">
    <div class="messages container mt-2">
      {% if messages %}
      {% for message in messages %}
      <div {% if message.tags %}
        class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}{% endif %}"
        role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
      </div>
      {% endfor %}
      {% endif %}
    </div>
    {% block body_block %} {% endblock %}

  </div>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>

</body>

</html>

e-com/templates/navbar.html
{% load static %}
{% load cart_tag %}
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <div class="container">
    <a class="navbar-brand font-weight-bold" style="font-size: 30px; font-family: Verdana, Geneva, Tahoma, sans-serif;"
      href="{% url 'app_shop:home' %}"> <img src="{% static 'images/e-logo.png' %}"
        style="width: 30px; height:30px; margin-top: -5px;">E-com</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span
        class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        {% if request.user.user_type == "Buyer" %}
        <li class="nav-item">
          <a href="{% url 'app_order:cart' %}" class="nav-link">
            <i class="fa fa-shopping-cart"></i> Cart
            <span class="badge badge-light">{{ request.user | cart_total }}</span>
          </a>
        </li>
        {% endif %}
        <li class="nav-item">

        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie"></i>
            {{request.user.profile.username}}</a>
          <div class="dropdown-menu" aria-labelledby="nabbarDropdown">
            <a class="dropdown-item" href="{% url 'app_login:profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'app_payment:orders' %}">Orders</a>
            {% if request.user.user_type == "Saller" %}
            <a class="dropdown-item" href="{% url 'app_shop:SallerUploadProduct' %}">Add Product</a>
            <a class="dropdown-item" href="{% url 'app_shop:sallerproductlist' %}">View Product List</a>
            <a class="dropdown-item" href="{% url 'app_shop:CreateCoupon' %}">Create Coupon</a>
            {% endif %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'app_login:logout' %}">Logout</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="{% url 'app_login:login' %}" class="btn btn-primary">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>